apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-killer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-killer
  template:
    metadata:
      labels:
        app: pod-killer
    spec:
      containers:
        - name: app
          image: ghcr.io/juanjo-vlc/flask-pod-killer:main
          ports:
            - containerPort: 5000
          env:
            - name: DEBUG
              value: True
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
